// Plain data file — no "use client", safe to import from server and client components alike

export type CalcMeta = {
  slug: string;
  label: string;
  subtitle: string;
  htmlFile: string;       // served statically from /public
  category: string;
  spec: string;
  status: "ready" | "wip" | "planned";
  group?: string;         // optional — calcs sharing a group are rendered as one expandable card
  keywords?: string[];    // extra search terms pulled from calc content
};

export const CALCS: CalcMeta[] = [
  // ── Wind / Loads ─────────────────────────────────────────────
  {
    slug: "diaphragm",
    label: "Rectangular Diaphragm Designer",
    subtitle: "Diaphragm unit shear · chord forces · shearwall reactions for rectangular diaphragms",
    htmlFile: "/Calcs/rectangular_diaphragm_calculator.html",
    category: "Wind / Loads",
    spec: "SDPWS 2021 / ASCE 7-16",
    status: "ready",
    keywords: ["diaphragm", "shearwall", "chord", "drag strut", "unit shear", "wind", "seismic", "lateral", "wood", "plywood", "OSB", "rectangular", "SDPWS"],
  },
  {
    slug: "wood-diaphragm",
    label: "Wood Diaphragm Designer",
    subtitle: "Blocked & unblocked WSP diaphragm — unit shear zones, chord forces, drag struts, deflection",
    htmlFile: "/Calcs/wood_diaphragm_designer.html",
    category: "Wind / Loads",
    spec: "SDPWS-21 §4.2 / ASCE 7-22",
    status: "ready",
    keywords: ["wood", "diaphragm", "WSP", "blocked", "unblocked", "sheathing", "fastener", "nailing", "chord", "drag strut", "deflection", "plywood", "OSB", "SDPWS", "lateral"],
  },
  {
    slug: "mwfrs-wind",
    label: "MWFRS Wind Pressure",
    subtitle: "Main wind-force resisting system — Directional Procedure, all heights, story shears, parapet",
    htmlFile: "/Calcs/asce716_mwfrs_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7-16 Ch.27 Pt.1",
    status: "ready",
    keywords: ["MWFRS", "wind", "pressure", "story shear", "parapet", "directional procedure", "Cp", "GCp", "velocity", "exposure", "building", "ASCE 7", "lateral force"],
  },
  {
    slug: "cc-wind",
    label: "C&C Wind Pressure",
    subtitle: "Components & cladding design pressures — all 6 ASCE 7-16 figures, log-linear GCp interpolation",
    htmlFile: "/Calcs/asce716_cc_wind_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7-16 Ch.30",
    status: "ready",
    keywords: ["components", "cladding", "C&C", "wind", "GCp", "effective wind area", "zone", "pressure", "ASCE 7", "roof", "wall", "cladding"],
  },
  // ── Connections ──────────────────────────────────────────────
  {
    slug: "base-plate",
    label: "RISA Table Import",
    subtitle: "Multi-member table format — load RISA Excel export to check all columns at once",
    htmlFile: "/Calcs/column_base_plate_v3.html",
    category: "Connections",
    spec: "AISC DG1",
    status: "ready",
    group: "Base Plate Designers",
    keywords: ["column", "anchor bolt", "axial", "shear", "moment", "multi-member", "table", "envelope", "concrete", "grout", "pedestal", "DG1"],
  },
  {
    slug: "base-plate-v1",
    label: "Single Base Plate",
    subtitle: "Axial · shear · moment · anchor bolt concrete checks (DG1 Ex. 4.4 & 4.10)",
    htmlFile: "/Calcs/column_base_plate_calculator.html",
    category: "Connections",
    spec: "AISC DG1",
    status: "ready",
    group: "Base Plate Designers",
    keywords: ["column", "anchor bolt", "axial", "shear", "moment", "single", "bearing", "concrete", "grout", "pedestal", "DG1"],
  },
  {
    slug: "gusset",
    label: "HSS Brace Gusset",
    subtitle: "Whitmore · buckling · weld · bolt group",
    htmlFile: "/Calcs/HSS_column_brace_gusset_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["HSS", "brace", "gusset plate", "Whitmore", "fillet weld", "bolt", "buckling", "A500", "A36", "column", "lateral brace", "block shear", "AISC 360"],
  },
  {
    slug: "brace-connection",
    label: "Channel Brace Connection",
    subtitle: "Channel brace bolted to gusset — shear + tension",
    htmlFile: "/Calcs/channel_brace_connection_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["channel", "HSS", "brace", "eccentric", "torsion", "stiffener", "shear", "tension", "bolt", "connection", "out-of-plane", "AISC 360"],
  },
  // ── Members ──────────────────────────────────────────────────
  {
    slug: "joist-bearing",
    label: "Channel Joist Bearing",
    subtitle: "Web yielding · crippling · bearing plate",
    htmlFile: "/Calcs/channel_joist_bearing_calculator.html",
    category: "Members",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["channel", "joist", "bearing", "web yielding", "crippling", "flange bending", "torsion", "stiffener", "DG9", "AISC 360", "steel beam"],
  },
  {
    slug: "unistrut",
    label: "Unistrut P1000HS",
    subtitle: "Load capacity and span check",
    htmlFile: "/Calcs/unistrut_p1000hs_calculator.html",
    category: "Members",
    spec: "Unistrut Tables",
    status: "ready",
    keywords: ["unistrut", "P1000", "strut channel", "span", "load capacity", "framing", "support", "mechanical", "hanger", "strut"],
  },
  // ── Members ──────────────────────────────────────────────────
  {
    slug: "stacked-headers",
    label: "Stacked Headers & Studs",
    subtitle: "Accumulates DL · LL · Snow jamb loads floor-by-floor at stacked openings",
    htmlFile: "/Calcs/stacked_headers_studs_calculator.html",
    category: "Members",
    spec: "ASCE 7-22",
    status: "ready",
    keywords: ["wood", "header", "jamb", "stud", "lumber", "opening", "window", "door", "load accumulation", "dead load", "live load", "snow", "NDS", "floor"],
  },
  {
    slug: "stacked-shearwall",
    label: "Stacked Shearwall Designer",
    subtitle: "Perforated shear wall method · multi-story uplift · sheathing capacity · hold-downs",
    htmlFile: "/Calcs/stacked_shearwall_calculator.html",
    category: "Members",
    spec: "SDPWS 2021",
    status: "ready",
    keywords: ["shearwall", "wood", "perforated", "multi-story", "uplift", "holdown", "hold-down", "sheathing", "nailing", "SDPWS", "Simpson", "HDUE", "lateral", "sill plate"],
  },
  // ── Masonry — CMU Walls (listed first) ───────────────────────
  {
    slug: "masonry-reinforced-wall-asd",
    label: "Reinforced Masonry Wall — ASD",
    subtitle: "8″ / 10″ / 12″ CMU · single & double reinforced · partial & full grout · axial, OOP flexure & deflection, OOP shear, combined, in-plane shear",
    htmlFile: "/Calcs/masonry_reinforced_wall_asd_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG-2022 Ch. 11",
    status: "ready",
    group: "CMU Walls",
    keywords: ["masonry", "CMU", "reinforced", "wall", "ASD", "allowable stress", "shear wall", "out-of-plane", "in-plane", "flexure", "axial", "combined", "TMS 402", "MDG", "partial grout", "full grout", "wind", "seismic", "8 inch", "10 inch", "12 inch", "deflection"],
  },
  {
    slug: "unreinforced-cmu-wall",
    label: "Unreinforced CMU Bearing Wall",
    subtitle: "4\u2033 & 6\u2033 CMU \u2014 combined axial + wind flexure, net tension \u00B7 ASD unity check",
    htmlFile: "/Calcs/unreinforced_cmu_wall_asd_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 \u00A78.2 / MDG-2022",
    status: "ready",
    group: "CMU Walls",
    keywords: ["CMU", "masonry", "unreinforced", "bearing wall", "wind", "flexure", "axial", "ASD", "unity check", "4 inch", "6 inch", "TMS 402", "net tension", "block"],
  },
  {
    slug: "masonry-lintel-jamb",
    label: "Masonry Lintel + Jamb Designer",
    subtitle: "Lintel gravity (REK-06) · lintel OOP C&C wind · reinforced jamb (REK-04) \u00B7 ASD unity check",
    htmlFile: "/Calcs/masonry_lintel_jamb_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 \u00A78.3 / MDG REK-04 & REK-06",
    status: "ready",
    group: "CMU Openings",
    keywords: ["masonry", "CMU", "lintel", "jamb", "reinforced", "ASD", "flexure", "shear", "out-of-plane", "OOP", "wind", "C&C", "components cladding", "biaxial", "TMS 402", "MDG", "REK-04", "REK-06", "opening", "door", "window", "bearing"],
  },
  // ── Masonry — Connections & Details ──────────────────────────
  {
    slug: "masonry-bearing-uplift",
    label: "Masonry Bearing Plate with Uplift",
    subtitle: "Effective bearing area (layouts A/B/C) · bearing stress · headed stud uplift (ASD)",
    htmlFile: "/Calcs/masonry_bearing_uplift_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG REK-07/09",
    status: "ready",
    keywords: ["masonry", "CMU", "bearing", "bearing plate", "uplift", "steel beam", "seat", "headed stud", "ASD", "TMS 402", "MDG", "block wall", "bearing stress"],
  },
  {
    slug: "masonry-anchor-bolt",
    label: "Masonry Anchor Bolt (Shear Connection)",
    subtitle: "Headed bolt SD — tension, shear (all 4 modes) & interaction per Eq. 9-8",
    htmlFile: "/Calcs/masonry_anchor_bolt_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 SD / MDG REK-08",
    status: "ready",
    keywords: ["masonry", "CMU", "anchor bolt", "headed bolt", "tension", "shear", "strength design", "LRFD", "TMS 402", "block shear", "interaction"],
  },
  {
    slug: "masonry-lap-length",
    label: "Masonry Development & Lap Splice",
    subtitle: "Deformed bar development length & Class A lap splice per Eq. 6-2",
    htmlFile: "/Calcs/masonry_lap_length_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG REK-10",
    status: "ready",
    keywords: ["masonry", "CMU", "development length", "lap splice", "rebar", "reinforcement", "deformed bar", "TMS 402", "Class A", "cover", "bar size"],
  },
  // ── Steel / Members ──────────────────────────────────────────
  {
    slug: "steel-joist-selector",
    label: "Steel Joist Selector — SJI Load Tables",
    subtitle: "K, KCS & LH series — ASD load combos · auto-selects lightest joist · 3 alternatives · gravity & uplift reactions",
    htmlFile: "/Calcs/steel_joist_selector_calculator.html",
    category: "Members",
    spec: "SJI K/KCS/LH · IBC/ASCE 7",
    status: "ready",
    keywords: ["joist", "steel joist", "open web", "K-series", "KCS", "LH", "longspan", "SJI", "roof", "floor", "span", "spacing", "uniform load", "deflection", "reaction", "uplift", "ASD", "load table", "bar joist"],
  },
  {
    slug: "web-opening",
    label: "W-Shape Beam Web Opening",
    subtitle: "Multiple openings · Vierendeel tee action · bearing & tee section checks · LRFD & ASD load combinations",
    htmlFile: "/Calcs/web_opening_calculator.html",
    category: "Members",
    spec: "AISC DG2",
    status: "ready",
    keywords: ["web opening", "W-shape", "beam", "Vierendeel", "tee section", "opening", "floor beam", "penetration", "AISC DG2", "Design Guide 2", "LRFD", "ASD", "ASCE 7", "gravity", "simply supported", "cantilever"],
  },
  {
    slug: "f11-plate-bending",
    label: "Rectangular Plate / Bar Bending & Compression",
    subtitle: "Strong-axis LTB · weak-axis flexure · axial compression · combined loading per H1",
    htmlFile: "/Calcs/F11_plate_bending_calculator.html",
    category: "Members",
    spec: "AISC 360-22 §F11 / E3 / H1",
    status: "ready",
    keywords: ["plate", "flat bar", "bending", "LTB", "lateral torsional buckling", "compression", "combined loading", "H1", "F11", "rectangular", "AISC 360", "strong axis", "weak axis"],
  },
  // ── Steel / Connections ───────────────────────────────────────
  {
    slug: "web-stiffener",
    label: "I-Shaped Member Stiffener Design",
    subtitle: "Proportioning limits · web shear & openings · transverse stiffener check · local web yielding",
    htmlFile: "/Calcs/web_stiffener_calculator.html",
    category: "Connections",
    spec: "AISC 360-22 §F13.2 / G2 / J10.2",
    status: "ready",
    keywords: ["stiffener", "web", "I-shape", "W-shape", "beam", "girder", "proportioning", "opening", "local web yielding", "transverse", "AISC 360", "shear", "F13", "G2", "J10"],
  },
  {
    slug: "column-bearing-plate-slab",
    label: "Column Bearing Plate on Slab",
    subtitle: "Bearing pressure · plate bending · two-way punching shear · one-way slab shear",
    htmlFile: "/Calcs/column_bearing_plate_slab_calculator.html",
    category: "Connections",
    spec: "AISC DG01 / ACI 318-19",
    status: "ready",
    keywords: ["column", "bearing plate", "concrete slab", "punching shear", "two-way shear", "one-way shear", "ACI 318", "bearing pressure", "AISC DG1", "plate bending"],
  },
  // ── Cold-Formed Steel (CFS) ───────────────────────────────────
  {
    slug: "cfs-stud-combined",
    label: "CFS Stud — Combined Axial + Bending",
    subtitle: "SSMA stud section dropdown · global / local / distortional compression · LTB · flexure · combined H1.2",
    htmlFile: "/Calcs/CFS_Stud_Combined_Bending_Compression.html",
    category: "CFS",
    spec: "AISI S100-16 §E2 / E3 / E4 / F2 / F3 / F4 / G2 / H1.2",
    status: "ready",
    group: "CFS Members",
    keywords: ["cold-formed", "CFS", "stud", "SSMA", "axial", "compression", "bending", "combined", "H1.2", "LTB", "lateral torsional buckling", "distortional", "local buckling", "flexural-torsional", "AISI S100", "light gauge", "framing"],
  },
  {
    slug: "cfs-weld",
    label: "CFS Weld Connection Designer",
    subtitle: "All 8 weld types — fillet, arc spot, arc seam, flare bevel, flare V-groove, groove butt · ASD + LRFD",
    htmlFile: "/Calcs/AISI_S100_16_Weld_Calculator.html",
    category: "CFS",
    spec: "AISI S100-16 Chapter J",
    status: "ready",
    group: "CFS Connections",
    keywords: ["cold-formed", "CFS", "weld", "fillet", "arc spot", "puddle weld", "arc seam", "flare bevel", "flare V-groove", "groove butt", "AISI S100", "thin sheet", "light gauge"],
  },
  {
    slug: "cfs-screw",
    label: "CFS Screw Connection Designer",
    subtitle: "Tilting/bearing · pull-out · pull-over · screw tension · combined V+T interactions · ASD + LRFD",
    htmlFile: "/Calcs/AISI_S100_16_Screw_Calculator.html",
    category: "CFS",
    spec: "AISI S100-16 J4.3–J4.5 / J6",
    status: "ready",
    group: "CFS Connections",
    keywords: ["cold-formed", "CFS", "screw", "self-drilling", "self-tapping", "tilting", "bearing", "pull-out", "pull-over", "AISI S100", "sheet metal", "light gauge", "combined"],
  },
  // ── Integrated / Multi-System ────────────────────────────────
  {
    slug: "headers-gradebeam-pier",
    label: "Headers → Grade Beams → Piers",
    subtitle: "Integrated load path: wood opening loads → ACI concrete grade beams → drilled pier foundation with minimum embedment depth",
    htmlFile: "/Calcs/headers_gradebeam_pier_calculator.html",
    category: "Integrated",
    spec: "NDS 2018 / ACI 318-19 / ACI 336.3R",
    status: "ready",
    keywords: ["headers", "grade beam", "pier", "drilled pier", "concrete beam", "wood header", "opening", "load path", "NDS", "ACI 318", "ACI 336", "foundation", "integrated", "stacked", "jamb", "embedment", "skin friction", "end bearing", "belled pier", "straight shaft", "stud wall", "LRFD", "ASD"],
  },
  // ── Concrete ─────────────────────────────────────────────────
  {
    slug: "concrete-beam-design",
    label: "Rectangular Concrete Beam Design",
    subtitle: "Nonprestressed rectangular beam — flexure, shear, deflection, bar spacing, crack control & development length",
    htmlFile: "/Calcs/concrete_beam_design_calculator.html",
    category: "Concrete",
    spec: "ACI 318-19",
    status: "ready",
    keywords: ["concrete", "beam", "rectangular", "ACI 318", "flexure", "shear", "deflection", "rebar", "reinforcement", "crack control", "development length", "stirrups", "LRFD", "nonprestressed", "moment", "As", "bar spacing", "d/c ratio"],
  },
  // ── Foundations ──────────────────────────────────────────────
  {
    slug: "holdown-footing",
    label: "Shearwall Holdown Footing",
    subtitle: "Spread footing for shearwall uplift",
    htmlFile: "/Calcs/SW_HoldownFooting_Calculator.html",
    category: "Foundations",
    spec: "ACI 318-19",
    status: "ready",
    keywords: ["footing", "spread footing", "holdown", "hold-down", "shearwall", "uplift", "foundation", "ACI 318", "concrete", "soil", "bearing capacity", "ENERCALC"],
  },
  {
    slug: "wri-stiffened-slab",
    label: "WRI Stiffened Slab Foundation",
    subtitle: "Ribbed slab-on-ground · WRI Design Guide · beam depth, flexure & deflection",
    htmlFile: "/Calcs/wri_stiffened_slab_calculator.html",
    category: "Foundations",
    spec: "WRI / ACI 318-19",
    status: "ready",
    keywords: ["slab", "foundation", "ribbed", "WRI", "stiffened slab", "grade beam", "slab-on-ground", "flexure", "deflection", "expansive soil", "ACI 318", "post-tension"],
  },
  {
    slug: "straight-shaft-pier",
    label: "Straight Shaft Pier (Drilled Pier)",
    subtitle: "Skin friction · end bearing · uplift · ASD rebar · ACI 318-19 min. reinforcing",
    htmlFile: "/Calcs/straight_shaft_pier_calculator.html",
    category: "Foundations",
    spec: "ACI 318-19 / ASD",
    status: "ready",
    group: "Drilled Pier Designers",
    keywords: ["pier", "drilled pier", "caisson", "skin friction", "end bearing", "uplift", "rebar", "ACI 318", "geotechnical", "straight shaft", "deep foundation"],
  },
  {
    slug: "belled-pier",
    label: "Belled Pier (Bell Caisson)",
    subtitle: "Bell end bearing · frustum volume · uplift · ASD rebar · ACI 318-19 min. reinforcing",
    htmlFile: "/Calcs/belled_pier_calculator.html",
    category: "Foundations",
    spec: "ACI 318-19 / ASD",
    status: "ready",
    group: "Drilled Pier Designers",
    keywords: ["pier", "drilled pier", "bell", "belled", "caisson", "underreamed", "end bearing", "uplift", "rebar", "ACI 318", "geotechnical", "deep foundation", "frustum"],
  },
];
