// Plain data file — no "use client", safe to import from server and client components alike
// (registry updated 2026-06-11: steel connection calcs from audit)

export type CalcMeta = {
  slug: string;
  label: string;
  subtitle: string;
  htmlFile: string;       // served statically from /public
  category: string;
  spec: string;
  status: "ready" | "wip" | "planned";
  group?: string;         // optional — calcs sharing a group are rendered as one expandable card
  keywords?: string[];    // extra search terms pulled from calc content
};

export const CALCS: CalcMeta[] = [
  // ── Wind / Loads ─────────────────────────────────────────────
  {
    slug: "diaphragm",
    label: "Rectangular Diaphragm Designer",
    subtitle: "Diaphragm unit shear · chord forces · shearwall reactions for rectangular diaphragms",
    htmlFile: "/Calcs/rectangular_diaphragm_calculator.html",
    category: "Wind / Loads",
    spec: "SDPWS 2021 / ASCE 7-16",
    status: "ready",
    keywords: ["diaphragm", "shearwall", "chord", "drag strut", "unit shear", "wind", "seismic", "lateral", "wood", "plywood", "OSB", "rectangular", "SDPWS"],
  },
  {
    slug: "wood-diaphragm",
    label: "Wood Diaphragm Designer",
    subtitle: "Blocked & unblocked WSP diaphragm — unit shear zones, chord forces, drag struts, deflection",
    htmlFile: "/Calcs/wood_diaphragm_designer.html",
    category: "Wind / Loads",
    spec: "SDPWS-21 §4.2 / ASCE 7-22",
    status: "ready",
    keywords: ["wood", "diaphragm", "WSP", "blocked", "unblocked", "sheathing", "fastener", "nailing", "chord", "drag strut", "deflection", "plywood", "OSB", "SDPWS", "lateral"],
  },
  {
    slug: "mwfrs-wind",
    label: "MWFRS Wind Pressure",
    subtitle: "Main wind-force resisting system — Directional Procedure, all heights, story shears, parapet",
    htmlFile: "/Calcs/asce716_mwfrs_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7-16 Ch.27 Pt.1",
    status: "ready",
    keywords: ["MWFRS", "wind", "pressure", "story shear", "parapet", "directional procedure", "Cp", "GCp", "velocity", "exposure", "building", "ASCE 7", "lateral force"],
  },
  {
    slug: "cc-wind",
    label: "C&C Wind Pressure",
    subtitle: "Components & cladding design pressures — all 6 ASCE 7-16 figures, log-linear GCp interpolation",
    htmlFile: "/Calcs/asce716_cc_wind_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7-16 Ch.30",
    status: "ready",
    keywords: ["components", "cladding", "C&C", "wind", "GCp", "effective wind area", "zone", "pressure", "ASCE 7", "roof", "wall", "cladding"],
  },
  {
    slug: "snow-load",
    label: "Snow Load Calculator",
    subtitle: "Flat/sloped roof snow pf=0.7·Ce·Ct·Is·pg, drift (hd eq.), sliding & unbalanced",
    htmlFile: "/Calcs/snow_load_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7 Ch. 7",
    status: "ready",
    keywords: ["snow", "drift", "sliding", "unbalanced", "pf", "pg", "Ce", "Ct", "roof", "parapet", "ASCE 7", "leeward", "windward"],
  },
  {
    slug: "asce-irregularity",
    label: "Seismic Irregularity Checker",
    subtitle: "Horizontal & vertical structural irregularities per ASCE 7 Tables 12.3-1 / 12.3-2",
    htmlFile: "/Calcs/asce_irregularity_calculator.html",
    category: "Wind / Loads",
    spec: "ASCE 7 §12.3",
    status: "ready",
    keywords: ["seismic", "irregularity", "torsional", "reentrant", "soft story", "weak story", "diaphragm discontinuity", "ASCE 7", "12.3"],
  },
  {
    slug: "beam-formulas",
    label: "Beam Analysis (Formula Cases)",
    subtitle: "Standard beam cases — moment, shear, reactions, deflection (AISC Table 3-23 formulas)",
    htmlFile: "/Calcs/beam_calculator.html",
    category: "Members",
    spec: "AISC Manual Table 3-23",
    status: "ready",
    keywords: ["beam", "deflection", "moment", "shear", "reaction", "simply supported", "cantilever", "fixed", "propped", "uniform", "point load", "formulas"],
  },
  {
    slug: "counterfort-wall",
    label: "Counterfort Retaining Wall (Bay)",
    subtitle: "Counterfort wall bay — overturning, sliding, bearing (middle-third / effective width)",
    htmlFile: "/Calcs/counterfort_bay_v4.html",
    category: "Foundations",
    spec: "ACI 318 / soil mechanics",
    status: "ready",
    keywords: ["retaining wall", "counterfort", "overturning", "sliding", "bearing", "active pressure", "stem", "heel", "toe", "footing"],
  },
  {
    slug: "multi-story-holdown",
    label: "Multi-Story Shear Wall Hold-Downs",
    subtitle: "4-story stacked shear wall — cumulative overturning, hold-down/strap D/C per story",
    htmlFile: "/Calcs/4_story_shear_wall_calculator.html",
    category: "Members",
    spec: "SDPWS / Simpson catalog",
    status: "ready",
    keywords: ["shear wall", "holdown", "hold-down", "strap", "HDU", "CMST", "overturning", "multi-story", "stacked", "uplift", "Simpson"],
  },
  {
    slug: "tji-purlin",
    label: "TJI Purlin Selector",
    subtitle: "TJI roof purlin — manufacturer table capacities, two-phase check incl. shear deflection",
    htmlFile: "/Calcs/tji-purlin-calculator.html",
    category: "Members",
    spec: "Weyerhaeuser TJI tables",
    status: "ready",
    keywords: ["TJI", "purlin", "I-joist", "roof", "Weyerhaeuser", "engineered lumber", "deflection", "span", "wood"],
  },
  // ── Connections ──────────────────────────────────────────────
  {
    slug: "base-plate",
    label: "RISA Table Import",
    subtitle: "Multi-member table format — load RISA Excel export to check all columns at once",
    htmlFile: "/Calcs/column_base_plate_v3.html",
    category: "Connections",
    spec: "AISC DG1",
    status: "ready",
    group: "Base Plate Designers",
    keywords: ["column", "anchor bolt", "axial", "shear", "moment", "multi-member", "table", "envelope", "concrete", "grout", "pedestal", "DG1"],
  },
  {
    slug: "base-plate-v1",
    label: "Single Base Plate",
    subtitle: "Axial · shear · moment · anchor bolt concrete checks (DG1 Ex. 4.4 & 4.10)",
    htmlFile: "/Calcs/column_base_plate_calculator.html",
    category: "Connections",
    spec: "AISC DG1",
    status: "ready",
    group: "Base Plate Designers",
    keywords: ["column", "anchor bolt", "axial", "shear", "moment", "single", "bearing", "concrete", "grout", "pedestal", "DG1"],
  },
  {
    slug: "gusset",
    label: "HSS Brace Gusset",
    subtitle: "Whitmore · buckling · weld · bolt group",
    htmlFile: "/Calcs/HSS_column_brace_gusset_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["HSS", "brace", "gusset plate", "Whitmore", "fillet weld", "bolt", "buckling", "A500", "A36", "column", "lateral brace", "block shear", "AISC 360"],
  },
  {
    slug: "brace-connection",
    label: "Channel Brace Connection",
    subtitle: "Channel brace bolted to gusset — shear + tension",
    htmlFile: "/Calcs/channel_brace_connection_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["channel", "HSS", "brace", "eccentric", "torsion", "stiffener", "shear", "tension", "bolt", "connection", "out-of-plane", "AISC 360"],
  },
  {
    slug: "hss-to-hss-branch",
    label: "HSS-to-HSS Branch (T/Y/X)",
    subtitle: "Rectangular HSS branch to chord — axial · Chapter K3",
    htmlFile: "/Calcs/HSS_to_HSS_branch_connection_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    group: "HSS Connections",
    keywords: ["HSS", "branch", "chord", "T-connection", "Y-connection", "X-connection", "truss", "plastification", "punching", "sidewall", "K3", "DG24", "AISC 360"],
  },
  {
    slug: "w-to-hss-column",
    label: "W-Beam to HSS Column (DG24 Ex 4.3)",
    subtitle: "Directly welded W to HSS — chord wall local yielding K1-7",
    htmlFile: "/Calcs/W_beam_to_HSS_column_calculator.html",
    category: "Connections",
    spec: "AISC 360-22",
    status: "ready",
    group: "HSS Connections",
    keywords: ["W-shape", "HSS", "column", "moment", "directly welded", "flange", "local yielding", "K1", "DG24", "Example 4.3", "AISC 360"],
  },
  {
    slug: "through-plate",
    label: "Through-Plate Moment Connection (DG24 Ex 4.2)",
    subtitle: "Through-plate FR moment connection to HSS column — plate yield/rupture, bolt shear, bearing/tearout",
    htmlFile: "/Calcs/through_plate_calculator.html",
    category: "Connections",
    spec: "AISC 360-22 / DG24",
    status: "ready",
    group: "HSS Connections",
    keywords: ["through plate", "HSS", "moment connection", "FR", "bolted", "splice plate", "tensile rupture", "bearing", "tearout", "DG24", "Example 4.2", "J4", "J3"],
  },
  {
    slug: "directly-welded-hss",
    label: "Directly Welded W to HSS (React)",
    subtitle: "Moment-transfer flange checks incl. punching shear — DG24 Ex 4.3 methodology",
    htmlFile: "/Calcs/directly_welded_HSS_connection_calculator.html",
    category: "Connections",
    spec: "AISC 360-22 / DG24",
    status: "ready",
    group: "HSS Connections",
    keywords: ["directly welded", "HSS", "W-beam", "moment", "K1-7", "punching shear", "local yielding", "DG24", "Example 4.3"],
  },
  {
    slug: "hss-connection-complete",
    label: "HSS Connection — Complete Checks (React)",
    subtitle: "Full limit-state suite for W-to-HSS welded connection per DG24",
    htmlFile: "/Calcs/hss_connection_complete_calculator.html",
    category: "Connections",
    spec: "AISC 360-22 / DG24",
    status: "ready",
    group: "HSS Connections",
    keywords: ["HSS", "connection", "limit states", "local yielding", "punching", "sidewall", "DG24", "K1", "complete"],
  },
  {
    slug: "large-moment-base-plate",
    label: "Large Moment Base Plate (DG1 Ex 4.6/4.7)",
    subtitle: "Small & large moment base plates — bearing, e/ecrit, anchor tension, plate thickness, LRFD+ASD",
    htmlFile: "/Calcs/large_moment_base_plate.html",
    category: "Connections",
    spec: "AISC DG1 2nd Ed",
    status: "ready",
    keywords: ["base plate", "large moment", "anchor rod", "bearing", "ecrit", "DG1", "Example 4.7", "column base", "concrete", "grout"],
  },
  // ── Members ──────────────────────────────────────────────────
  {
    slug: "joist-bearing",
    label: "Channel Joist Bearing",
    subtitle: "Web yielding · crippling · bearing plate",
    htmlFile: "/Calcs/channel_joist_bearing_calculator.html",
    category: "Members",
    spec: "AISC 360-22",
    status: "ready",
    keywords: ["channel", "joist", "bearing", "web yielding", "crippling", "flange bending", "torsion", "stiffener", "DG9", "AISC 360", "steel beam"],
  },
  {
    slug: "unistrut",
    label: "Unistrut P1000HS",
    subtitle: "Load capacity and span check",
    htmlFile: "/Calcs/unistrut_p1000hs_calculator.html",
    category: "Members",
    spec: "Unistrut Tables",
    status: "ready",
    keywords: ["unistrut", "P1000", "strut channel", "span", "load capacity", "framing", "support", "mechanical", "hanger", "strut"],
  },
  // ── Members ──────────────────────────────────────────────────
  {
    slug: "stacked-headers",
    label: "Stacked Headers & Studs",
    subtitle: "Accumulates DL · LL · Snow jamb loads floor-by-floor at stacked openings",
    htmlFile: "/Calcs/stacked_headers_studs_calculator.html",
    category: "Members",
    spec: "ASCE 7-22",
    status: "ready",
    keywords: ["wood", "header", "jamb", "stud", "lumber", "opening", "window", "door", "load accumulation", "dead load", "live load", "snow", "NDS", "floor"],
  },
  {
    slug: "stacked-shearwall",
    label: "Stacked Shearwall Designer",
    subtitle: "Perforated shear wall method · multi-story uplift · sheathing capacity · hold-downs",
    htmlFile: "/Calcs/stacked_shearwall_calculator.html",
    category: "Members",
    spec: "SDPWS 2021",
    status: "ready",
    keywords: ["shearwall", "wood", "perforated", "multi-story", "uplift", "holdown", "hold-down", "sheathing", "nailing", "SDPWS", "Simpson", "HDUE", "lateral", "sill plate"],
  },
  // ── Masonry — CMU Walls (listed first) ───────────────────────
  {
    slug: "masonry-reinforced-wall-asd",
    label: "Reinforced Masonry Wall — ASD",
    subtitle: "8″ / 10″ / 12″ CMU · single & double reinforced · partial & full grout · axial, OOP flexure & deflection, OOP shear, combined, in-plane shear",
    htmlFile: "/Calcs/masonry_reinforced_wall_asd_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG-2022 Ch. 11",
    status: "ready",
    group: "CMU Walls",
    keywords: ["masonry", "CMU", "reinforced", "wall", "ASD", "allowable stress", "shear wall", "out-of-plane", "in-plane", "flexure", "axial", "combined", "TMS 402", "MDG", "partial grout", "full grout", "wind", "seismic", "8 inch", "10 inch", "12 inch", "deflection"],
  },
  {
    slug: "unreinforced-cmu-wall",
    label: "Unreinforced CMU Bearing Wall",
    subtitle: "4″ & 6″ CMU — combined axial + wind flexure, net tension · ASD unity check",
    htmlFile: "/Calcs/unreinforced_cmu_wall_asd_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 §8.2 / MDG-2022",
    status: "ready",
    group: "CMU Walls",
    keywords: ["CMU", "masonry", "unreinforced", "bearing wall", "wind", "flexure", "axial", "ASD", "unity check", "4 inch", "6 inch", "TMS 402", "net tension", "block"],
  },
  {
    slug: "masonry-lintel-jamb",
    label: "Masonry Lintel + Jamb Designer",
    subtitle: "Lintel gravity (REK-06) · lintel OOP C&C wind · reinforced jamb (REK-04) · ASD unity check",
    htmlFile: "/Calcs/masonry_lintel_jamb_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 §8.3 / MDG REK-04 & REK-06",
    status: "ready",
    group: "CMU Openings",
    keywords: ["masonry", "CMU", "lintel", "jamb", "reinforced", "ASD", "flexure", "shear", "out-of-plane", "OOP", "wind", "C&C", "components cladding", "biaxial", "TMS 402", "MDG", "REK-04", "REK-06", "opening", "door", "window", "bearing"],
  },
  {
    slug: "masonry-lintel-asd",
    label: "Masonry Lintel — ASD",
    subtitle: "Reinforced CMU lintel — flexure §8.3.2, shear §8.3.5 w/ M/(Vd) interpolation, gravity + uplift",
    htmlFile: "/Calcs/masonry_lintel_asd_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 §8.3 ASD",
    status: "ready",
    group: "CMU Openings",
    keywords: ["masonry", "CMU", "lintel", "ASD", "flexure", "shear", "uplift", "TMS 402", "opening", "beam", "reinforced", "grouted"],
  },
  {
    slug: "masonry-asd-general",
    label: "Masonry ASD Design (General Section)",
    subtitle: "Reinforced masonry section — ASD flexure + shear with Fv M/(Vd) interpolation",
    htmlFile: "/Calcs/masonry_asd_design_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 Ch. 8 ASD",
    status: "ready",
    keywords: ["masonry", "CMU", "ASD", "flexure", "shear", "reinforced", "section", "TMS 402", "kd", "transformed section", "allowable stress"],
  },
  // ── Masonry — Connections & Details ──────────────────────────
  {
    slug: "masonry-bearing-uplift",
    label: "Masonry Bearing Plate with Uplift",
    subtitle: "Effective bearing area (layouts A/B/C) · bearing stress · headed stud uplift (ASD)",
    htmlFile: "/Calcs/masonry_bearing_uplift_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG REK-07/09",
    status: "ready",
    keywords: ["masonry", "CMU", "bearing", "bearing plate", "uplift", "steel beam", "seat", "headed stud", "ASD", "TMS 402", "MDG", "block wall", "bearing stress"],
  },
  {
    slug: "masonry-anchor-bolt",
    label: "Masonry Anchor Bolt (Shear Connection)",
    subtitle: "Headed bolt SD — tension, shear (all 4 modes) & interaction per Eq. 9-8",
    htmlFile: "/Calcs/masonry_anchor_bolt_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 SD / MDG REK-08",
    status: "ready",
    keywords: ["masonry", "CMU", "anchor bolt", "headed bolt", "tension", "shear", "strength design", "LRFD", "TMS 402", "block shear", "interaction"],
  },
  {
    slug: "masonry-top-wall-anchor",
    label: "Masonry Top-of-Wall Anchor",
    subtitle: "Headed bolt ASD — tension (masonry breakout + steel), shear (4 modes) & combined interaction",
    htmlFile: "/Calcs/masonry_anchor_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 §6.3 & §8.1.4.3",
    status: "ready",
    group: "CMU Connections",
    keywords: ["masonry", "CMU", "anchor", "anchor bolt", "headed bolt", "tension", "shear", "ASD", "allowable stress", "breakout", "interaction", "top of wall", "fastener", "TMS 402", "embedment", "projected area", "Apt", "edge distance", "IBC 1605.2"],
  },
  {
    slug: "masonry-lap-length",
    label: "Masonry Development & Lap Splice",
    subtitle: "Deformed bar development length & Class A lap splice per Eq. 6-2",
    htmlFile: "/Calcs/masonry_lap_length_calculator.html",
    category: "Masonry",
    spec: "TMS 402-22 / MDG REK-10",
    status: "ready",
    keywords: ["masonry", "CMU", "development length", "lap splice", "rebar", "reinforcement", "deformed bar", "TMS 402", "Class A", "cover", "bar size"],
  },
  // ── Steel / Members ──────────────────────────────────────────
  {
    slug: "steel-joist-selector",
    label: "Steel Joist Selector — SJI Load Tables",
    subtitle: "K, KCS & LH series — ASD load combos · auto-selects lightest joist · 3 alternatives · gravity & uplift reactions",
    htmlFile: "/Calcs/steel_joist_selector_calculator.html",
    category: "Members",
    spec: "SJI K/KCS/LH · IBC/ASCE 7",
    status: "ready",
    keywords: ["joist", "steel joist", "open web", "K-series", "KCS", "LH", "longspan", "SJI", "roof", "floor", "span", "spacing", "uniform load", "deflection", "reaction", "uplift", "ASD", "load table", "bar joist"],
  },
  {
    slug: "web-opening",
    label: "W-Shape Beam Web Opening",
    subtitle: "Multiple openings · Vierendeel tee action · bearing & tee section checks · LRFD & ASD load combinations",
    htmlFile: "/Calcs/web_opening_calculator.html",
    category: "Members",
    spec: "AISC DG2",
    status: "ready",
    keywords: ["web opening", "W-shape", "beam", "Vierendeel", "tee section", "opening", "floor beam", "penetration", "AISC DG2", "Design Guide 2", "LRFD", "ASD", "ASCE 7", "gravity", "simply supported", "cantilever"],
  },
  {
    slug: "f11-plate-bending",
    label: "Rectangular Plate / Bar Bending & Compression",
    subtitle: "Strong-axis LTB · weak-axis flexure · axial compression · combined loading per H1",
    htmlFile: "/Calcs/F11_plate_bending_calculator.html",
    category: "Members",
    spec: "AISC 360-22 §F11 / E3 / H1",
    status: "ready",
    keywords: ["plate", "flat bar", "bending", "LTB", "lateral torsional buckling", "compression", "combined loading", "H1", "F11", "rectangular", "AISC 360", "strong axis", "weak axis"],
  },
  // ── Steel / Connections ───────────────────────────────────────
  {
    slug: "web-stiffener",
    label: "I-Shaped Member Stiffener Design",
    subtitle: "Proportioning limits · web shear & openings · transverse stiffener check · local web yielding",
    htmlFile: "/Calcs/web_stiffener_calculator.html",
    category: "Connections",
    spec: "AISC 360-22 §F13.2 / G2 / J10.2",
    status: "ready",
    keywords: ["stiffener", "web", "I-shape", "W-shape", "beam", "girder", "proportioning", "opening", "local web yielding", "transverse", "AISC 360", "shear", "F13", "G2", "J10"],
  },
  {
    slug: "column-bearing-plate-slab",
    label: "Column Bearing Plate on Slab",
    subtitle: "Bearing pressure · plate bending · two-way punching shear · one-way slab shear",
    htmlFile: "/Calcs/column_bearing_plate_slab_calculator.html",
    category: "Connections",
    spec: "AISC DG01 / ACI 318-19",
    status: "ready",
    keywords: ["column", "bearing plate", "concrete slab", "punching shear", "two-way shear", "one-way shear", "ACI 318", "bearing pressure", "AISC DG1", "plate bending"],
  },
  // ── Cold-Formed Steel (CFS) ───────────────────────────────────
  {
    slug: "cfs-stud-combined",
    label: "CFS Stud — Combined Axial + Bending",
    subtitle: "SSMA stud section dropdown · global / local / distortional compression · LTB · flexure · combined H1.2",
    htmlFile: "/Calcs/CFS_Stud_Combined_Bending_Compression.html",
    category: "CFS",
    spec: "AISI S100-16 §E2 / E3 / E4 / F2 / F3 / F4 / G2 / H1.2",
    status: "ready",
    group: "CFS Members",
    keywords: ["cold-formed", "CFS", "stud", "SSMA", "axial", "compression", "bending", "combined", "H1.2", "LTB", "lateral torsional buckling", "distortional", "local buckling", "flexural-torsional", "AISI S100", "light gauge", "framing"],
  },
  {
    slug: "cfs-wall-opening",
    label: "CFS Wall Opening — Header / Sill / Jamb",
    subtitle: "Exterior wall opening: header tracks (lateral wind) + vertical studs (gravity) · sill · jamb combined bending+axial with explicit jamb length · full SSMA dropdowns",
    htmlFile: "/Calcs/CFS_Wall_Opening_Header_Sill_Jamb_calculator.html",
    category: "CFS",
    spec: "AISI S100-16 §B1.2 / C3.1.1 / C3.2 / C3.3 / E2-E3 / C5.2",
    status: "ready",
    group: "CFS Members",
    keywords: ["cold-formed", "CFS", "wall", "opening", "header", "sill", "jamb", "track", "stud", "SSMA", "lateral", "wind", "gravity", "combined", "bending", "axial", "compression", "C5.2", "effective width", "AISI S100", "light gauge", "framing", "window", "door", "lintel", "box header"],
  },
  {
    slug: "cfs-weld",
    label: "CFS Weld Connection Designer",
    subtitle: "All 8 weld types — fillet, arc spot, arc seam, flare bevel, flare V-groove, groove butt · ASD + LRFD",
    htmlFile: "/Calcs/AISI_S100_16_Weld_Calculator.html",
    category: "CFS",
    spec: "AISI S100-16 Chapter J",
    status: "ready",
    group: "CFS Connections",
    keywords: ["cold-formed", "CFS", "weld", "fillet", "arc spot", "puddle weld", "arc seam", "flare bevel", "flare V-groove", "groove butt", "AISI S100", "thin sheet", "light gauge"],
  },
  {
    slug: "cfs-screw",
    label: "CFS Screw Connection Designer",
    subtitle: "Tilting/bearing · pull-out · pull-over · screw tension · combined V+T interactions · ASD + LRFD",
    htmlFile: "/Calcs/AISI_S100_16_Screw_Calculator.html",
    category: "CFS",
    spec: "AISI S100-16 J4.3–J4.5 / J6",
    status: "ready",
    group: "CFS Connections",
    keywords: ["cold-formed", "CFS", "screw", "self-drilling", "self-tapping", "tilting", "bearing", "pull-out", "pull-over", "AISI S100", "sheet metal", "light gauge", "combined"],
  },
  // ── Integrated / Multi-System ────────────────────────────────
  {
    slug: "headers-gradebeam-pier",
    label: "Headers → Grade Beams → Piers",
    subtitle: "Integrated load path: wood opening loads → ACI concrete grade beams → drilled pier foundation with minimum embedment depth",
    htmlFile: "/Calcs/headers_gradebeam_pier_calculator.html",
    category: "Integrated",
    spec: "NDS 2018 / ACI 318-19 / ACI 336.3R",
    status: "ready",
    keywords: ["headers", "grade beam", "pier", "drilled pier", "concrete beam", "wood header", "opening", "load path", "NDS", "ACI 318", "ACI 336", "foundation", "integrated", "stacked", "jamb", "embedment", "skin friction", "end bearing", "belled pier", "straight shaft", "stud wall", "LRFD", "ASD"],
  },
  // ── Concrete ─────────────────────────────────────────────────
  {
    slug: "concrete-beam-design",
    label: "Rectangular Concrete Beam Design",
    subtitle: "Nonprestressed rectangular beam — flexure, shear, deflection, bar spacing, crack control & development length",
    htmlFile: "/Calcs/concrete_beam_design_calculator.html",
    category: "Concrete",
    spec: "ACI 318-19",
    status: "ready",
    keywords: ["concrete", "beam", "rectangular", "ACI 318", "flexure", "shear", "deflection", "rebar", "reinforcement", "crack control", "development length", "stirrups", "LRFD", "nonprestressed", "moment", "As", "bar spacing", "d/c ratio"],
  },
  // ── Foundations ──────────────────────────────────────────────
  {
    slug: "holdown-footing",
    label: "Shearwall Holdown Footing",
    subtitle: "Spread footing for shearwall uplift",
    htmlFile: "/Calcs/SW_HoldownFooting_Calculator.html",
    category: "Foundations",
    spec: "ACI 318-19",
    status: "ready",
    keywords: ["footing", "spread footing", "holdown", "hold-down", "shearwall", "uplift", "foundation", "ACI 318", "concrete", "soil", "bearing capacity", "ENERCALC"],
  },
  {
    slug: "wri-stiffened-slab",
    label: "WRI Stiffened Slab Foundation",
    subtitle: "Ribbed slab-on-ground · WRI Design Guide · beam depth, flexure & deflection",
    htmlFile: "/Calcs/wri_stiffened_slab_calculator.html",
    category: "Foundations",
    spec: "WRI / ACI 318-19",
    status: "ready",
    keywords: ["slab", "foundation", "ribbed", "WRI", "stiffened slab", "grade beam", "slab-on-ground", "flexure", "deflection", "expansive soil", "ACI 318", "post-tension"],
  },
  {
    slug: "straight-shaft-pier",
    label: "Straight Shaft Pier (Drilled Pier)",
    subtitle: "Skin friction · end bearing · uplift · ASD rebar · ACI 318-19 min. reinforcing",
    htmlFile: "/Calcs/straight_shaft_pier_calculator.html",
    category: "Foundations",
    spec: "ACI 318-19 / ASD",
    status: "ready",
    group: "Drilled Pier Designers",
    keywords: ["pier", "drilled pier", "caisson", "skin friction", "end bearing", "uplift", "rebar", "ACI 318", "geotechnical", "straight shaft", "deep foundation"],
  },
  {
    slug: "belled-pier",
    label: "Belled Pier (Bell Caisson)",
    subtitle: "Bell end bearing · frustum volume · uplift · ASD rebar · ACI 318-19 min. reinforcing",
    htmlFile: "/Calcs/belled_pier_calculator.html",
    category: "Foundations",
    spec: "ACI 318-19 / ASD",
    status: "ready",
    group: "Drilled Pier Designers",
    keywords: ["pier", "drilled pier", "bell", "belled", "caisson", "underreamed", "end bearing", "uplift", "rebar", "ACI 318", "geotechnical", "deep foundation", "frustum"],
  },
];
